-- Blog post excerpt + updated_at
ALTER TABLE blog_posts
  ADD COLUMN IF NOT EXISTS excerpt VARCHAR(500) DEFAULT NULL AFTER cover_image_url,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
